name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - gh-pages-src

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        git checkout gh-pages-src
        pip install -r requirements.txt

    - name: Build and deploy
      run: |
        mkdocs build
        git config user.name "Juice Brenner Build Bot"
        git config user.email "seattlecommunitynetwork.org"
        git checkout gh-pages
        git add --all
        git stash
        rm -rf *
        git stash pop
        mv site/* .
        rm -r site
        git add --all
        git commit -m "Yet another automated deployment"
        git push

        

